name: Deploy to GitLab Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # This step creates a .gitlab-ci.yml file that will be used by GitLab to deploy the app
      - name: Create GitLab CI file
        run: |
          cat > .gitlab-ci.yml <<EOF
          pages:
            stage: deploy
            script:
              - mkdir -p public
              - cp -r dist/* public/
            artifacts:
              paths:
                - public
            only:
              - main
              - master
          EOF

      - name: Push to GitLab
        uses: actions-x/commit@v6
        with:
          email: "github-actions-bot@example.com"
          name: "GitHub Actions Bot"
          message: "Build and update for GitLab Pages deployment"
          files: ".gitlab-ci.yml dist/"
          token: ${{ secrets.GITLAB_TOKEN }}
          repository: ${{ secrets.GITLAB_REPOSITORY_URL }}
          branch: ${GITHUB_REF#refs/heads/}
